// <auto-generated />
using Api_Crud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api_Crud.Migrations
{
    [DbContext(typeof(MedidorContextcs))]
    partial class MedidorContextcsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api_Crud.Models.Medidor", b =>
                {
                    b.Property<int>("MedidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MedidorConsumo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedidorStatus")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedidorTipo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.HasKey("MedidorId");

                    b.ToTable("Medidores");
                });
#pragma warning restore 612, 618
        }
    }
}
